RA_id: "Aws-USA-RA"
universe_id: "swarmchestrate_universe"
credentials:
  provider: "aws"
  access_key: "YOUR_AWS_ACCESS_KEY"
  secret_key: "YOUR_AWS_SECRET_KEY"
api_port: 
p2p_port: 
domain: "0.0.0.0"
bootstrap_peers:
  - "" 
