id: "Aws-RA2"
capacity_id: "aws_ra2_provider"
universe_id: "swarmchestrate_universe"
credentials:
  provider: "aws"
  access_key: "YOUR_AWS_ACCESS_KEY"
  secret_key: "YOUR_AWS_SECRET_KEY"
api_port: ""  # EC2 RA API port
p2p_port: ""  # EC2 RA P2P port  [listening port for other RAs to connect to]
domain: "0.0.0.0"  # Bind to all interfaces on EC2 (like we did before)
bootstrap_peers: []  # EC2 RA acts as server, no bootstrap needed
