id: "Aws-RA3"
capacity_id: "aws_ra3_provider"
universe_id: "swarmchestrate_universe"
credentials:
  provider: "aws"
  access_key: "YOUR_AWS_ACCESS_KEY"
  secret_key: "YOUR_AWS_SECRET_KEY"
api_port: ""
p2p_port: ""
bootstrap_peers: ["IP":p2p_port"]  # AWS-RA3 connects to  (AWS-RA2)
domain: "0.0.0.0"  # Bind to all interfaces on EC2
